name: Bender CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Download Conan
      run: |
        python3 -m pip install --upgrade pip
        pip3 install conan
        conan --version
    - name: Conan install
      run: cd build && conan install .. --build missing
    - name: cmake
      run: cd build && cmake ..
    - name: make
      run: cd build && make
